#! /bin/sh

sxhkd &
setxkbmap de &
sh /home/andreas/.config/nvidia/screen.sh
sh /home/andreas/.config/bspwm/autostart

bspc monitor DVI-D-0 -d I II III X
bspc monitor HDMI-0 -d IV V VI
bspc monitor DP-0 -d VII VIII IX 

bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# bspc rule -a (INSERT HERE) desktop='^8' state=floating follow=on
bspc rule -a lxappearance desktop='^4'
